### PR TITLE
test branch policy

### PR DESCRIPTION
**Pull request by aldelar**
## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ X] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by james-tn** [comment]
looks good

**Review by jpoetzinger — COMMENTED** [review]
looks good to me

**Comment by james-tn** [comment]
reopen it

**Comment by james-tn** [comment]
re-open

**Review by james-tn — APPROVED** [review]
This is ok

**Review by mpieler1 — APPROVED** [review]
Looks good!

**Pull request merged**
